projects:
  houseboard:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - amplify/**
    extensions:
      amplify:
        docsFilePath: src/graphql
        maxDepth: 5
extensions:
  amplify:
    version: 3
